/* Auto-generated by firealarm_c_exporter.py */
#ifndef FIREALARM_MODEL_H
#define FIREALARM_MODEL_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define INPUT_H 64
#define INPUT_W 48
#define INPUT_C 4
#define CONV1_OUT_C 8
#define CONV2_OUT_C 16
#define CONV3_OUT_C 32
#define FC1_OUT 16
#define NUM_CLASSES 3

#define CALIB_CROP_X 8.94624626e+00f
#define CALIB_CROP_Y 3.34024017e+00f
#define CALIB_CROP_W 1.54810014e+01f
#define CALIB_CROP_H 1.55725189e+01f

typedef struct {
    int class_id;
    float confidence;
    float probabilities[NUM_CLASSES];
    float logits[NUM_CLASSES];
} firealarm_prediction_t;

const char* firealarm_class_name(int class_id);
int firealarm_infer(const float input[INPUT_C * INPUT_H * INPUT_W], float logits[NUM_CLASSES]);
void firealarm_predict(const float input[INPUT_C * INPUT_H * INPUT_W], firealarm_prediction_t *prediction);

#ifdef __cplusplus
}
#endif

#endif /* FIREALARM_MODEL_H */
